### ISSUE TITLE
NOT NULL omejitev pri referencah

### ISSUE THREAD

**Issue by majbc1999** [nezakrzan/Nepremicninske-agencije#2]
Opazil sem napakico, ki se vam ponavlja: ko ustvarite tabele s stolpcem, ki se sklicuje na neko drugo tabelo, morate dodati še omejitev `NOT NULL`. Sicer bo baza v tem stolpcu omogočanje vstavljanje vrednosti `NULL`. Na primer, zaenkrat imate:
```sql
        CREATE TABLE agencija (
            id SERIAL UNIQUE PRIMARY KEY NOT NULL,
            ime TEXT NOT NULL,
            mesto TEXT NOT NULL,
            postna_st INTEGER REFERENCES posta(postna_stevilka)
            );
```
V tem primeru bo ukaz `INSERT INTO agencija(ime, mesto) VALUES ('Agencija 1', 'Ljubljana')` uspešno dodal vrstico v tabelo brez vrednosti v stolpcu `postna_st`. Predlagam, da povsod, kjer je to smiselno, referencam dodate omejitev `NOT NULL`, na primer:
```sql
        CREATE TABLE agencija (
            id SERIAL UNIQUE PRIMARY KEY NOT NULL,
            ime TEXT NOT NULL,
            mesto TEXT NOT NULL,
            postna_st INTEGER REFERENCES posta(postna_stevilka) NOT NULL
            );
```
Potem, ko to storite, seveda zbrišite tabele na bazi in ponovno uvozite podatke.

**Comment by nezakrzan** [comment]
Hvala za komentar. Smo spremenile.
