### ISSUE TITLE
Vključitev bootstrapa

### ISSUE THREAD

**Issue by majbc1999** [nezakrzan/Nepremicninske-agencije#3]
Trenutno se vam celotna spletna stran pomakne na skrajno levo. Problem je, da v `osnova.html` ne uporabite kontejnerja. Če v `body`ju dodate kontejner, se vam izgled takoj polepša:
```html
<body>
<div class="container">

<h2>{{naslov}}</h2>

{{!base}}

</div>
</body>
```

**Comment by Nina2809** [comment]
Hvala za opozorilo, smo popravile. :)
