### ISSUE TITLE
Delovanje registracije

### ISSUE THREAD

**Issue by Nina2809** [nezakrzan/Nepremicninske-agencije#4]
Prosile bi pomoč pri zapisu registracije, težavo imamo namreč, da po vpisu vseh podatkov osebe ne vpiše v tabelo in se registracija ne dokonča.
Že v naprej hvala za pomoč!

**Comment by majbc1999** [comment]
Živjo! Našel sem nekaj napak v vaši kodi, zaradi katerih vam registracija ne deluje:

1. Ko se registrirate in iščete uporabnika v bazi, morate napako vrniti, ko ga najdete (saj je v tem primeru že registriran). Torej, v vrstici 118 `nepremicninske_agencije.py`:
```python
if uporabnik is not None:
        nastaviSporocilo('Registracija ni možna') 
        redirect('/registracija')
        return
```
2. V tabeli `agent` imate stolpec z imenom `id_agent` in ne `id`, podobno ni stolpca `placa`, pač pa `plača`. Torej, v vrstici 136 `nepremicninske_agencije.py`:
```python
    if tip == 'agent':
        cur.execute("""INSERT INTO agent
                (id_agent, agencija, plača)
                VALUES (%s, %s, %s)""", (id, agencija, placa))
```
3.  V `registracija.html` morate popraviti gnezdenje formov (posameznih formov oz. obrazcev praviloma ne gnezdimo). V 130. vrstici spremenite
```html
    <div>
      <input type = "radio" name = "tip" value = "agent"> Agent
      <input type = "radio" name = "tip" value = "komitent"> Komitent
    </div>
```
4. V 125. vrstici `registracija.html` ste pozabile zamenjati paramater `name` iz `agent` v `placa`:
```html
<input id="placa" name="placa" type="number" class="form-control" 
```
Upam, da vam bo po tem popravkih delovalo (meni deluje).

**Comment by Nina2809** [comment]
Smo popravile in vse deluje, najlepša hvala za pomoč.
