### ISSUE TITLE
Brisanje nepremičnine

### ISSUE THREAD

**Issue by Nina2809** [nezakrzan/Nepremicninske-agencije#5]
Potrebovale bi pomoč pri brisanju nepremičnine. Kljub temu, da smo uredile, da ko izbrišemo nepremičnino, da se izbriše tudi komitent, nam še vedno javlja napako, da izbris ni mogoč, ker se v komitentu sklicujemo na nepremičnino, ki bi jo rade izbrisale.
Že v naprej hvala za pomoč!

**Comment by majbc1999** [comment]
### 1. Brisanje nepremičnine
Težava je, da želite iz tabele `komitent` izbrisati vrstice, kjer se kupuje nepremičnina, ki jo želite izbrisati. Trenutno brišete iz tabele komitent vrstice, ki imajo v `id_komitent` vrednost `id`, namesto v `kupuje_nepremicnino`. To lahko rešite tako (namesto vaših vrstic 505-515):
```python
cur.execute("DELETE FROM hisa WHERE id_hisa =%s" % (id))
cur.execute("DELETE FROM stanovanje WHERE id_stanovanje=%s" % (id))
cur.execute("DELETE FROM komitent WHERE kupuje_nepremicnino=%s" % (id))
cur.execute("DELETE FROM nepremicnina WHERE id =%s" % (id))
conn.commit()
```
### 2. Težava z vpisovanjem emša

Poleg tega sem opazil pri vas težavo: če med registracijo vpišem svoj emšo, mi vrne napako
```python
psycopg2.errors.NumericValueOutOfRange: value "1812999500000" is out of range for type integer
LINE 3:                 VALUES ('1812999500000', 'Maj', 'Gaberšček',...
```
To se zgodi, ker imate stolpec `id` v tabeli `oseba` tipa `SERIAL`, ki omogoča samo števila do $2^{31} - 1$. Svetujem vam, da stolpcu spremenite tip na `BIGINT`, ki omogoča precej večja števila (do $2^{63} - 1$). To lahko storite z ukazi:
```sql
ALTER TABLE oseba ALTER COLUMN id TYPE BIGINT;
ALTER TABLE agent ALTER COLUMN id_agent TYPE BIGINT;
ALTER TABLE komitent ALTER COLUMN id_komitent TYPE BIGINT;
```

**Comment by jaanos** [comment]
Seveda pazite še na to, da ne odpirate možnosti napadov [SQL](https://en.wikipedia.org/wiki/SQL_injection) [injection](https://xkcd.com/327/) - tako kot drugod podajte `id` v seznamu kot drugi argument metode `execute` (tj., ga ne vstavljate v niz s `%` ali na kak drug način), npr.
```python
cur.execute("DELETE FROM hisa WHERE id_hisa = %s", [id])
```

Kar se tiče EMŠOv, kot je opozoril @majbc1999, bi predlagal, da jih imate kar v poljih tipa `TEXT`. Morda bo celo bolje, da pustite `id` v tabeli `oseba` tipa `SERIAL` (in tako ostanejo nespremenjene reference na ta stolpec), sam EMŠO pa imate v svojem stolpcu (z omejitvama `NOT NULL UNIQUE`, da se vrednosti ne bodo ponavljale), ID-je pa pustite, da se vam sami generirajo.

Še to: vidim, da na več mestih uporabljate funkcijo `url`, ki pa ji podaste kar pot (tj., začne se z `/`). Prvi argument funkcije `url` naj bo kar ime ustrezne funkcije - tako se bodo zgradile ustrezne poti tudi, ko boste aplikacijo poganjale na Binderju. Seveda na isti način gradite poti tudi v predlogah. Za več podrobnosti si poglejte MatejRojec/Gamma#1.

**Comment by Nina2809** [comment]
Hvala za pomoč, smo popravile tako izbris nepremičnine, kot tudi url povezave.
