### ISSUE TITLE
Zaključek projekta in ne delujoč binder

### ISSUE THREAD

**Issue by Nina2809** [nezakrzan/Nepremicninske-agencije#6]
Pred zaključkom imamo težavo še, da binder ne dela, kljub temu, da smo popravile, da so v url povezavah imena funkcij. Prosile bi za pomoč, kako lahko projekt popravimo, da bo tudi to delovalo. 

Sicer se nam zdi projekt primeren za oddajo, bomo pa vesele predlogov za izboljšavo.

**Comment by majbc1999** [comment]
Živjo! Imam sicer še nekaj predlogov za popravek in sicer:

### 1. Piškotki pri dodajanju komitentov in agentov

Zaenkrat imate naslednjo situacijo: Ko je prijavljen agent s svojim računom in se odloči dodajati komitenta, se zgodi, da je nato (po dodajanju komitenta) vpisan kot komitent, ki ga je ravnokar dodal. Podoben problem se zgodi, če dodamo agenta. Nato smo namreč vpisani kot tisti, ki ga dodajamo, kar pa ni ravno intuitivno. Težavo vam povzročata vrstici 294 in 299, kjer med dodajanjem komitenta nastavite piškotek na njegovo uporabniško ime: `response.set_cookie('uporabnisko_ime', uporabnisko_ime, secret=skrivnost) ` . Podobno se vam zgodi v vrsticah 477 in 482, pri dodajanju agenta: vrstica `response.set_cookie('uporabnisko_ime', uporabnisko_ime, secret=skrivnost)` je odveč. Ko izbrišete te štiri vrstice, bo ta težava odpravljena.

### 2. Izginevanje orodne vrstica

Zaenkrat vam orodna vrstica izgine, če kliknemo na `Nepremičnine` -> `Hiše` ali `Nepremičnine` -> `Stanovanja`, tako da bi bilo to dobro popraviti. Sicer to naredite podobno, kakor v preostanku projekta

### 3. Sprememba gesla

Pri spremembi gesla se geslo izpiše v navadni obliki, kot text, namesto črnih pikic. To popravite tako, da tip inputa v `spremeni_geslo.html` nastavite `password`:
```html
            <input id="geslo" name="geslo" type="password" class="form-control" required
                oninput="this.setCustomValidity('')"
                oninvalid="this.setCustomValidity('Obvezno polje')"
                />
```
Seveda podobno naredite tudi v polju, kjer morate geslo ponovno vpisati:
```html
<input id="geslo2" name="geslo2" type="password" class="form-control" required
                oninput="this.setCustomValidity('')"
                oninvalid="this.setCustomValidity('Obvezno polje')"
                />
```

### 4. Binder

Vidim, da ste povsod pravilno uporabljali funkcijo `url`, zato ne vem zakaj, binder trenutno ne dela. @jaanos, imaš mogoče ti kakšno rešitev tukaj?

### 5. Redirect po registraciji

Zaenkrat se vam v registraciji cookie nastavi na uporabnika, ki se je registriral, vseeno pa nas vrže nazaj na prijavo. Morate se odločiti za eno od naslednjih dveh opcij:
- ali se mora po registraciji uporabnik nato še prijaviti (v tem primeru pustite redirect na prijavo in samo izbrišete vrstice, kjer nastavite cookie: vrstici 152 in 162), 
- ali pa ga po registraciji raje redirectajte na stran `podatki_prijavljenega`

Razen teh petih težav, se meni zdi dobro narejeno in vse dela.

**Comment by Nina2809** [comment]
Hvala za tvoje predloge za izboljšavo, smo jih upoštevale in projekt popravile.

**Comment by OkornA18** [comment]
Hvala za vso pomoč. Menimo, da je to torej naša končna različica projekta, zato bi Vas prosile, da dodate povezavo na repozitorij za zagovore.

**Comment by jaanos** [comment]
Sem zdaj pognal na Binderju, pa vidim, da registracija ne deluje. Težava je tukaj:
https://github.com/nezakrzan/Nepremicninske-agencije/blob/38f009366788072430dab3f97fed0daa54ad377d/views/registracija.html#L4
Seveda mora biti `url` znotraj zavitih oklepajev, tako kot drugod.

**Comment by Nina2809** [comment]
Hvala za opozorilo, smo popravile.

**Comment by majbc1999** [comment]
Sem pregledal projekt in sedaj tudi na binderju vse deluje tako kot mora. Tako da jih lahko dodaš na repozitorij ali pa jim posodobiš povezavo, @jaanos.

**Comment by jaanos** [comment]
Sem dodal povezavo na repozitorij za zagovore. Če boste do zagovora še kaj spreminjale, javite, da posodobim povezavo.
